name: Deploy to Windows Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: Install Posh-SSH
      shell: pwsh
      run: Install-Module -Name Posh-SSH -Force

    - name: Deploy to Windows Server
      shell: pwsh
      run: |
        $remoteHost = "${{ secrets.TEST_DEPLOY_HOST }}"
        $remoteUsername = "${{ secrets.TEST_DEPLOY_USER }}"
        $remotePassword = "${{ secrets.TEST_DEPLOY_PASSWORD }}"
        $localPath = "${{ github.workspace }}/dist"
        $remotePath = "${{ secrets.TEST_DEPLOY_TARGET }}"

        # Create a new SSH session
        $secpasswd = ConvertTo-SecureString $remotePassword -AsPlainText -Force
        $credentials = New-Object System.Management.Automation.PSCredential -ArgumentList ($remoteUsername, $secpasswd)
        $session = New-SSHSession -ComputerName $remoteHost -Credential $credentials

        # Copy files to remote server
        Copy-Item -Path $localPath/* -Destination $remotePath -ToSession $session

        # Close SSH session
        Remove-PSSession -Session $session