name: Deploy to Windows Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: Deploy to Windows Server
      shell: pwsh
      run: |
        $remoteHost = "${{ secrets.TEST_DEPLOY_HOST }}"
        $remoteUsername = "${{ secrets.TEST_DEPLOY_USER }}"
        $remotePassword = "${{ secrets.TEST_DEPLOY_PASSWORD }}"
        $localPath = "${{ github.workspace }}/dist"
        $remotePath = "${{ secrets.TEST_DEPLOY_TARGET }}"

        # Create a new SSH session
        $session = New-SSHSession -ComputerName $serverAddress -Credential (Get-Credential -UserName $remoteUsername -Password $remotePassword)

        # Copy files to remote server
        Copy-Item -Path $localPath/* -Destination $remotePath -ToSession $session

        # Close SSH session
        Remove-PSSession -Session $session